### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by V-FOR-VEND3TTA** [V-FOR-VEND3TTA/bootstrap-admin-theme#10]
To make your theme fully responsive, especially for mobile devices, here are a few changes and improvements you can apply:

### 1. **Adjust Sidebar Responsiveness**
When the screen size is small, the sidebar should collapse automatically. You can hide the sidebar and allow it to toggle in and out based on screen width.

#### Update Sidebar CSS for Mobile View:
```css
@media (max-width: 768px) {
  #sidebar {
    position: fixed;
    left: -250px;
    top: 0;
    height: 100%;
    transition: all 0.3s ease;
  }

  #sidebar.collapsed {
    left: 0;
  }

  #content {
    margin-left: 0;
    width: 100%;
  }
}
```

### 2. **Full-Width Content on Mobile**
Ensure the content takes the full width when the sidebar is hidden on smaller screens.

#### Adjust Content CSS:
```css
@media (max-width: 768px) {
  #content {
    margin-left: 0;
    padding: 15px;
  }

  #content.full-width {
    margin-left: 0;
  }

  .btn {
    margin: 0;
  }
}
```

### 3. **Optimize Table Views for Mobile**
Tables can become unreadable on mobile. Use the **Bootstrap table-responsive** class to make them scrollable on smaller screens.

#### Ensure Tables Are Responsive:
You already have this in your code for tables:
```html
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <!-- Table Content -->
  </table>
</div>
```
This will allow horizontal scrolling when viewed on smaller screens.

### 4. **Cards Responsiveness**
For metrics cards (Sales, Orders, Revenue, etc.), you want them to stack on smaller screens.

#### Adjust Card Columns for Small Screens:
```html
<div class="row">
  <div class="col-md-3 col-sm-6 mb-4">
    <!-- Card -->
  </div>
  <div class="col-md-3 col-sm-6 mb-4">
    <!-- Card -->
  </div>
  <!-- Additional cards here -->
</div>
```
The `col-sm-6` will make each card take 50% width on small screens, and `col-md-3` will make it 25% width on medium and larger screens.

### 5. **Navbar and Filter Responsiveness**
For the navbar and filters, ensure that they stack properly on small screens.

#### Update Navbar and Filter Styling:
```css
@media (max-width: 768px) {
  .navbar .navbar-nav {
    display: flex;
    flex-direction: column;
    align-items: start;
  }

  .row.m-4 {
    margin: 0;
  }

  .col-md-4 {
    margin-bottom: 15px;
  }
}
```

### 6. **Toggle Sidebar on Smaller Screens**
Ensure the sidebar toggles correctly with the **hamburger menu** on small screens using the existing `#sidebarToggle` button.

This will allow the sidebar to slide in from the left when toggled, making the layout more mobile-friendly.

### Recap:
- **Sidebar**: Collapses on smaller screens, can be toggled in/out.
- **Content**: Takes full width on smaller screens.
- **Cards**: Stack vertically on small screens using `col-sm-*` classes.
- **Tables**: Remain responsive with horizontal scrolling enabled.
- **Navbar and Filters**: Stack vertically on small screens for better layout.
